
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN ATOMIC BOOL CHAN COMMA GT ID INT LBRACE LOCK LPAREN LT NUMBER PARALLEL RBRACE RECV RPAREN SEMI SEND SPAWN UNLOCKprogram : statementsstatements : statements statementstatements : statementstatement : INT ID ASSIGN expression SEMIstatement : CHAN LT type GT ID SEMIstatement : PARALLEL LBRACE statements RBRACEstatement : SPAWN LPAREN expression RPAREN SEMIstatement : LOCK LPAREN ID RPAREN SEMIstatement : UNLOCK LPAREN ID RPAREN SEMIstatement : ATOMIC LBRACE statements RBRACEstatement : SEND LPAREN ID COMMA expression RPAREN SEMIstatement : ID ASSIGN RECV LPAREN ID RPAREN SEMIstatement : ID ASSIGN expression SEMIexpression : NUMBERexpression : IDtype : INT'
    
_lr_action_items = {'INT':([0,2,3,13,16,17,21,30,34,38,40,44,46,49,50,51,54,56,57,],[4,4,-3,-2,29,4,4,4,4,-13,-6,-10,-4,-7,-8,-9,-5,-12,-11,]),'CHAN':([0,2,3,13,17,21,30,34,38,40,44,46,49,50,51,54,56,57,],[6,6,-3,-2,6,6,6,6,-13,-6,-10,-4,-7,-8,-9,-5,-12,-11,]),'PARALLEL':([0,2,3,13,17,21,30,34,38,40,44,46,49,50,51,54,56,57,],[7,7,-3,-2,7,7,7,7,-13,-6,-10,-4,-7,-8,-9,-5,-12,-11,]),'SPAWN':([0,2,3,13,17,21,30,34,38,40,44,46,49,50,51,54,56,57,],[8,8,-3,-2,8,8,8,8,-13,-6,-10,-4,-7,-8,-9,-5,-12,-11,]),'LOCK':([0,2,3,13,17,21,30,34,38,40,44,46,49,50,51,54,56,57,],[9,9,-3,-2,9,9,9,9,-13,-6,-10,-4,-7,-8,-9,-5,-12,-11,]),'UNLOCK':([0,2,3,13,17,21,30,34,38,40,44,46,49,50,51,54,56,57,],[10,10,-3,-2,10,10,10,10,-13,-6,-10,-4,-7,-8,-9,-5,-12,-11,]),'ATOMIC':([0,2,3,13,17,21,30,34,38,40,44,46,49,50,51,54,56,57,],[11,11,-3,-2,11,11,11,11,-13,-6,-10,-4,-7,-8,-9,-5,-12,-11,]),'SEND':([0,2,3,13,17,21,30,34,38,40,44,46,49,50,51,54,56,57,],[12,12,-3,-2,12,12,12,12,-13,-6,-10,-4,-7,-8,-9,-5,-12,-11,]),'ID':([0,2,3,4,13,15,17,18,19,20,21,22,23,30,34,37,38,39,40,44,45,46,49,50,51,54,56,57,],[5,5,-3,14,-2,24,5,24,32,33,5,35,24,5,5,47,-13,48,-6,-10,24,-4,-7,-8,-9,-5,-12,-11,]),'$end':([1,2,3,13,38,40,44,46,49,50,51,54,56,57,],[0,-1,-3,-2,-13,-6,-10,-4,-7,-8,-9,-5,-12,-11,]),'RBRACE':([3,13,30,34,38,40,44,46,49,50,51,54,56,57,],[-3,-2,40,44,-13,-6,-10,-4,-7,-8,-9,-5,-12,-11,]),'ASSIGN':([5,14,],[15,23,]),'LT':([6,],[16,]),'LBRACE':([7,11,],[17,21,]),'LPAREN':([8,9,10,12,25,],[18,19,20,22,37,]),'RECV':([15,],[25,]),'NUMBER':([15,18,23,45,],[27,27,27,27,]),'SEMI':([24,26,27,36,41,42,43,48,53,55,],[-15,38,-14,46,49,50,51,54,56,57,]),'RPAREN':([24,27,31,32,33,47,52,],[-15,-14,41,42,43,53,55,]),'GT':([28,29,],[39,-16,]),'COMMA':([35,],[45,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,17,21,],[2,30,34,]),'statement':([0,2,17,21,30,34,],[3,13,3,3,13,13,]),'expression':([15,18,23,45,],[26,31,36,52,]),'type':([16,],[28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','parser.py',12),
  ('statements -> statements statement','statements',2,'p_statements_multiple','parser.py',16),
  ('statements -> statement','statements',1,'p_statements_single','parser.py',20),
  ('statement -> INT ID ASSIGN expression SEMI','statement',5,'p_var_decl','parser.py',25),
  ('statement -> CHAN LT type GT ID SEMI','statement',6,'p_channel_decl','parser.py',29),
  ('statement -> PARALLEL LBRACE statements RBRACE','statement',4,'p_parallel_block','parser.py',33),
  ('statement -> SPAWN LPAREN expression RPAREN SEMI','statement',5,'p_spawn','parser.py',37),
  ('statement -> LOCK LPAREN ID RPAREN SEMI','statement',5,'p_lock','parser.py',41),
  ('statement -> UNLOCK LPAREN ID RPAREN SEMI','statement',5,'p_unlock','parser.py',45),
  ('statement -> ATOMIC LBRACE statements RBRACE','statement',4,'p_atomic','parser.py',49),
  ('statement -> SEND LPAREN ID COMMA expression RPAREN SEMI','statement',7,'p_send','parser.py',53),
  ('statement -> ID ASSIGN RECV LPAREN ID RPAREN SEMI','statement',7,'p_recv','parser.py',57),
  ('statement -> ID ASSIGN expression SEMI','statement',4,'p_assign','parser.py',61),
  ('expression -> NUMBER','expression',1,'p_expression_literal','parser.py',65),
  ('expression -> ID','expression',1,'p_expression_id','parser.py',69),
  ('type -> INT','type',1,'p_type','parser.py',73),
]
